export const SELECT_COURSE = 'SELECT_COURSE';
export const UNSELECT_COURSE = 'UNSELECT_COURSE';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const SET_LOADING_STATE = 'SET_LOADIND_STATE';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOITIFICATION_SUCCESS';
